[package]
name = "axis-ai"
version = "0.1.2"
description = "Axis-AI — personal R&D for AI workflows"
authors = ["shaykh"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3          # default for release

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "axis_ai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
keyring = { version = "3", default-features = false, features = ["apple-native", "windows-native", "sync-secret-service"] }
uuid = { version = "1", features = ["v4"] }
# specific
tauri-build = "1.5"
tauri-macros = "1.4"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2.10.1"
sentry = "0.48.2"
tauri-plugin-process = "2.3.1"
tauri-plugin-os = "2.3.2"


[features]
custom-protocol = ["tauri/custom-protocol"]
